package fr.formation.inti.entities;
// Generated 22 ao�t 2019 15:31:06 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fiche generated by hbm2java
 */
@Entity
@Table(name = "fiche", catalog = "bdd")
public class Fiche implements java.io.Serializable {

	private Integer idfiche;
	private Patient patient;
	private Date dateRdv;
	private int poids;
	private String commentaireSante;
	private String commentaireActivite;
	private String commentaireGeneral;

	public Fiche() {
	}

	public Fiche(Patient patient, Date dateRdv, int poids) {
		this.patient = patient;
		this.dateRdv = dateRdv;
		this.poids = poids;
	}

	public Fiche(Patient patient, Date dateRdv, int poids, String commentaireSante, String commentaireActivite,
			String commentaireGeneral) {
		this.patient = patient;
		this.dateRdv = dateRdv;
		this.poids = poids;
		this.commentaireSante = commentaireSante;
		this.commentaireActivite = commentaireActivite;
		this.commentaireGeneral = commentaireGeneral;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfiche", unique = true, nullable = false)
	public Integer getIdfiche() {
		return this.idfiche;
	}

	public void setIdfiche(Integer idfiche) {
		this.idfiche = idfiche;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pId", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_rdv", nullable = false, length = 10)
	public Date getDateRdv() {
		return this.dateRdv;
	}

	public void setDateRdv(Date dateRdv) {
		this.dateRdv = dateRdv;
	}

	@Column(name = "poids", nullable = false)
	public int getPoids() {
		return this.poids;
	}

	public void setPoids(int poids) {
		this.poids = poids;
	}

	@Column(name = "commentaire_sante", length = 400)
	public String getCommentaireSante() {
		return this.commentaireSante;
	}

	public void setCommentaireSante(String commentaireSante) {
		this.commentaireSante = commentaireSante;
	}

	@Column(name = "commentaire_activite", length = 400)
	public String getCommentaireActivite() {
		return this.commentaireActivite;
	}

	public void setCommentaireActivite(String commentaireActivite) {
		this.commentaireActivite = commentaireActivite;
	}

	@Column(name = "commentaire_general", length = 1200)
	public String getCommentaireGeneral() {
		return this.commentaireGeneral;
	}

	public void setCommentaireGeneral(String commentaireGeneral) {
		this.commentaireGeneral = commentaireGeneral;
	}

}
