package fr.formation.inti.entities;
// Generated 22 ao�t 2019 15:31:06 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", catalog = "bdd")
public class Patient implements Serializable {

	private Integer pId;


	private String nom;
	private String prenom;
	private Date dateNaissance;
	private Integer taille;
	private Set<Fiche> fiches = new HashSet<Fiche>(0);

	
	
	public Patient() {
		super();
	}

	public Patient(String nom, String prenom, Date dateNaissance, Integer taille, Set<Fiche> fiches) {
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaissance = dateNaissance;
		this.taille = taille;
		this.fiches = fiches;
	}

	public Patient(int idfiche, String nom2, String prenom2, Date dateRdv) {
		// TODO Auto-generated constructor stub
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pId", unique = true, nullable = false)
	public Integer getpId() {
		return pId;
	}

	public void setpId(Integer pId) {
		this.pId = pId;
	}

	@Column(name = "nom", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_naissance", nullable = false, length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "taille")
	public Integer getTaille() {
		return this.taille;
	}

	public void setTaille(Integer taille) {
		this.taille = taille;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Fiche> getFiches() {
		return this.fiches;
	}

	public void setFiches(Set<Fiche> fiches) {
		this.fiches = fiches;
	}

}
